ALTER TABLE `employee_binding_codes` ADD CONSTRAINT `employee_binding_codes_employee_id_employees_id_fk` FOREIGN KEY (`employee_id`) REFERENCES `employees`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `employee_binding_codes` ADD CONSTRAINT `employee_binding_codes_created_by_users_id_fk` FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `employees` ADD CONSTRAINT `employees_department_id_departments_id_fk` FOREIGN KEY (`department_id`) REFERENCES `departments`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `schedule_change_logs` ADD CONSTRAINT `schedule_change_logs_period_id_schedule_periods_id_fk` FOREIGN KEY (`period_id`) REFERENCES `schedule_periods`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `schedule_change_logs` ADD CONSTRAINT `schedule_change_logs_operator_id_users_id_fk` FOREIGN KEY (`operator_id`) REFERENCES `users`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `schedule_entries` ADD CONSTRAINT `schedule_entries_period_id_schedule_periods_id_fk` FOREIGN KEY (`period_id`) REFERENCES `schedule_periods`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `schedule_entries` ADD CONSTRAINT `schedule_entries_employee_id_employees_id_fk` FOREIGN KEY (`employee_id`) REFERENCES `employees`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `schedule_entries` ADD CONSTRAINT `schedule_entries_shift_type_id_shift_types_id_fk` FOREIGN KEY (`shift_type_id`) REFERENCES `shift_types`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `schedule_periods` ADD CONSTRAINT `schedule_periods_department_id_departments_id_fk` FOREIGN KEY (`department_id`) REFERENCES `departments`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `schedule_periods` ADD CONSTRAINT `schedule_periods_last_published_by_users_id_fk` FOREIGN KEY (`last_published_by`) REFERENCES `users`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `schedule_publish_snapshots` ADD CONSTRAINT `schedule_publish_snapshots_period_id_schedule_periods_id_fk` FOREIGN KEY (`period_id`) REFERENCES `schedule_periods`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `schedule_publish_snapshots` ADD CONSTRAINT `schedule_publish_snapshots_published_by_users_id_fk` FOREIGN KEY (`published_by`) REFERENCES `users`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `shift_types` ADD CONSTRAINT `shift_types_department_id_departments_id_fk` FOREIGN KEY (`department_id`) REFERENCES `departments`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `users` ADD CONSTRAINT `users_employee_id_employees_id_fk` FOREIGN KEY (`employee_id`) REFERENCES `employees`(`id`) ON DELETE restrict ON UPDATE no action;